### ISSUE TITLE
Is it hard for MVDream to generate objects with low volume value in z axis?

### ISSUE THREAD

**Issue by Colezwhy** [bytedance/MVDream#33]
Just the same as in the title, in my trials on some objects with low volume values, like 'an empty plate', MVDream will not provide plausible results, but generate four views with the same face of the plate. Is it a universal issue of MVDream? I think might because of the  training dataset used? Since images with low z-axis value is seldomly rendered and trained on the Multi-view diffusion models.

**Comment by YuxuanSnow** [comment]
Did you try to add ", 3d asset" to the end of prompt? In paper authors mentioned that they use this to distinguish training data from objaverse (3D) and Laion (2D)

**Comment by Colezwhy** [comment]
> Did you try to add ", 3d asset" to the end of prompt? In paper authors mentioned that they use this to distinguish training data from objaverse (3D) and Laion (2D)

Thank you for your advise, but it seems that the produced multi-view images still perform the same attributes. And the reconstruction models will still produce 3D assets like a ball...
