### ISSUE TITLE
Generating from images

### ISSUE THREAD

**Issue by fefespn** [bytedance/MVDream#5]
Hi, 
Thanks for open sourcing your interesting hard working repo.

If I want to generate, let's say a chair, not from text prompt but with an input image,
(the motive is that I want to generate the same chair from different angles),
is there any technique to do it ? maybe changing little bit the diffuser model ? 
maybe inputing the noise as my image and in text prompt to put "chair" ?

**Comment by dragonlong** [comment]
I guess then you will want to check another work SyncDreamer, which can generate 16 views when giving 1 input image

**Comment by firasvree** [comment]
Oh ok thanks !! I liked the camera position optimization idea very much in your paper, SyncDreamer don't have this.
But ok I will think about a way to do it. thanks a lot !! good luck and have fun with your future work !!

**Comment by fefespn** [comment]
Oh ok thanks !! I liked the camera position optimization idea very much in your paper, SyncDreamer don't have this.
But ok I will think about a way to do it. thanks a lot !! good luck and have fun with your future work !!

**Comment by fefespn** [comment]
Oh ok thanks !! I liked the camera position optimization idea very much in your paper, SyncDreamer don't have this.
But ok I will think about a way to do it. thanks a lot !! good luck and have fun with your future work !!
