### ISSUE TITLE
Curious about the guidance scale used in your practice

### ISSUE THREAD

**Issue by lizhiqi49** [bytedance/MVDream#6]
Hi I have a question about the guidance scale.

I have tested the 2.1 model in my machine, and I find that the generation quality is very bad when guidance scale is relatively small (<20), and the quality was getting better and better as I added it along to 60. Below shows some of my testing results.

guidance scale = 10:
![image](https://github.com/bytedance/MVDream/assets/66679246/14d6424e-0d3e-4402-aafc-d85200a11581)

guidance scale = 15:
![image](https://github.com/bytedance/MVDream/assets/66679246/ae0d848d-042f-4c91-bc9b-2b5d0f630bc7)

guidance scale = 20:
![image](https://github.com/bytedance/MVDream/assets/66679246/0d0e618b-5c6f-4a40-a645-ad621ff706a9)

guidance scale = 40:
![image](https://github.com/bytedance/MVDream/assets/66679246/0e7a7d57-ef44-4384-b4ea-b91c828ddee6)

guidance scale = 60:
![image](https://github.com/bytedance/MVDream/assets/66679246/91e2baff-2831-4da1-a327-bcd8ff6efbc1)

Since I notice that in your T2I script you set the guidance scale defaultly as 10, I'm wondering if I made anything wrong.

And the backgrounds in the images above are all same brown color, is it correct?

**Comment by lizhiqi49** [comment]
And the sampler I used is 50-steps DDIM, with the prompt as "an astronaut riding a horse, 3d asset", and unconditional prompt as null ("").

**Comment by seasonSH** [comment]
which script are you using and did you change anything?

**Comment by lizhiqi49** [comment]
Actually its on my custom diffusers code since I'm more familiar with diffusers, I converted your ldm checkpoint to diffusers version... I think it unlikely generates such reasonable results if there is something wrong in my code.

But if the issue I met is unmatched with your practice, I will go to try your official code and check mine.

**Comment by lizhiqi49** [comment]
I've tried your official code and everything goes well, so there must be something wrong in my code, I'll check it. hhh
